# Generated by Django 6.0.6 on 2026-07-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_middle_name_user_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PARENT', 'Parent/Guardian'), ('STAFF', 'Staff/BHW'), ('ADMIN', 'Admin')], default='PARENT', max_length=10),
        ),
    ]
