# Generated by Django 6.0.6 on 2026-07-08 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid PH mobile number (e.g. 09171234567).', regex='^09\\d{9}$')]),
        ),
    ]
