# Generated by Django 6.0.6 on 2026-07-13 02:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def grandfather_existing_users(apps, schema_editor):
    """Accounts created before email verification existed never went through
    it and have no way to - mark them verified so this migration doesn't
    lock anyone out of an account they already had access to. Only accounts
    registered after this point require verification."""
    User = apps.get_model('accounts', 'User')
    User.objects.update(is_email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(grandfather_existing_users, migrations.RunPython.noop),
    ]
