# Generated by Django 6.0.6 on 2026-07-17 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_email_verified_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
