# Generated by Django 6.0.6 on 2026-07-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianprofile',
            name='relationship_to_child',
            field=models.CharField(max_length=50),
        ),
    ]
