# Generated by Django 6.0.6 on 2026-07-13 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_immunization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='enrollment.guardianprofile'),
        ),
    ]
